required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-5.0"
  name = "k8s.io/client-go"

[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  branch = "master"
  name = "github.com/golang/groupcache"
